name: 'Load GitHub Environment Variables'
description: 'Automatically loads all variables and secrets from a GitHub environment'
author: 'Justifi Tech'
branding:
  icon: 'download-cloud'
  color: 'blue'

inputs:
  environment-name:
    description: 'The name of the GitHub environment to load variables from'
    required: false
    default: 'staging'
  vars-json:
    description: 'JSON string of all variables (passed from workflow using toJSON(vars))'
    required: true
  secrets-json:
    description: 'JSON string of all secrets (passed from workflow using toJSON(secrets))'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Load all environment variables and secrets
      shell: bash
      env:
        VARS_JSON: '${{ inputs.vars-json }}'
        SECRETS_JSON: '${{ inputs.secrets-json }}'
      run: |
        # Export all variables from the GitHub environment
        if [ -n "$VARS_JSON" ] && [ "$VARS_JSON" != "{}" ]; then
          echo "📦 Loading environment variables..."
          echo "$VARS_JSON" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
            key="${line%%=*}"
            echo "  ✓ Loaded variable: $key"
          done
        else
          echo "ℹ️  No environment variables to load"
        fi

        # Export all secrets from the GitHub environment
        if [ -n "$SECRETS_JSON" ] && [ "$SECRETS_JSON" != "{}" ]; then
          echo "🔐 Loading secrets..."
          echo "$SECRETS_JSON" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
            key="${line%%=*}"
            echo "  ✓ Loaded secret: $key"
          done
        else
          echo "ℹ️  No secrets to load"
        fi

        echo "✅ Environment loading complete!"
