import { Source } from '@storybook/blocks';
import dedent from 'ts-dedent';

export const ExportedParts = ({ tags, component, compact }: { tags: string[]; component: string, compact: boolean }) => {
  return (
    <ul>
      {tags.map(text => {
        const splitText = text.split(':');
        const part = splitText[0];
        const description = splitText[1];
        return (
          <li key={part}>
            <strong>{part}</strong> {description ? '- ' + description : ''}
            <ExportedPartUsage component={component} tag={part} compact={compact} />
          </li>
        );
      })}
    </ul>
  );
};

export const ExportedPartUsage = ({ tag, component, compact }: { tag: string; component: string, compact?: boolean }) => (
  <Source
    dark
    language="css"
    code={dedent(`
      ${component || '*'}::part(${tag}) ${!compact ? `{
        color: red;
      }` : '{}'}
    `)}
  />
);

export const SummaryElement = (props: { title: string, children: any }) => {
  const { title, children } = props;

  return (
    <details style={{
      fontFamily: 'var(--bs-font-sans-serif)',
      color: '#2E3438',
      fontSize: '14px',
      cursor: 'pointer'
    }}>
      <summary>
        <b>{title}</b>
      </summary>

      {children}
    </details>
  );
};

export const AuthTokenDescription = () => (
  <>
    <strong>Create Access Token API</strong >: These tokens are generated by your backend services using the {' '}
    <a href="https://docs.justifi.tech/api-spec#tag/API-Credentials/operation/CreateAccessToken">
      Auth Token API
    </a>.
  </>
)


// A box where to render the component inside
export const ComponentBox = ({ children }: { children: any }) => {
  return (
    <div style={{
      border: '1px solid #E0E0E0',
      borderRadius: '4px',
      padding: '16px',
      marginBottom: '16px',
      marginTop: '20px'
    }}>
      {children}
    </div>
  );
}
