import { Component, h } from '@stencil/core';

@Component({
  tag: 'justifi-business-terms-conditions-text',
  styleUrl: 'business-terms-conditions-text.css'
})
export class BusinessTermsConditionsText {

  render() {
    return (
      <div class='terms-container'>
        <div class="card terms-conditions-card" part="card">
          <div class="card-body terms-card-body" part="card-body">
            <h2 class="card-title" part="card-title">JustiFi Technologies Inc. Terms and Conditions</h2>

            <p class='card-text' part="card-text">The Payment Terms and Conditions described herein constitute a legal agreement (“Agreement” or “JustiFi Technologies Inc. Terms”) between your business (the “Merchant”, “you” or “your”) and JustiFi Technologies Inc., organized under the laws of Minnesota with offices at 555 Vandalia St. St Paul, MN 55114, Suite #105. (“JustiFi”, “we”, “us”, or “our”).</p>

            <br />
            <h3 class="card-subtitle mb-2 text-muted" part="card-subtitle">A. The JustiFi Payments Service</h3>
            <br />

            <h4 class="card-subtitle" part="card-subtitle">Our Role</h4>
            <p class='card-text' part="card-text">The JustiFi Payments service (“JustiFi Payments” or the “Payments Services”) is a: (i) payment account boarding; (ii) payment underwriting; and, (iii) payment data transmission service that helps you integrate with a payment processor (the “Processor”), as described more fully in this Agreement.</p>
            <p class='card-text' part="card-text">JustiFi is not a bank, payment institution, or money services business, but is instead, respectively, a supplier of the JustiFi Platform Services supplied under the JustiFi Platform Terms and of the Payments Services under this Agreement.</p>

            <h4 class="card-subtitle" part="card-subtitle">The Processor</h4>
            <p>JustiFi provides a managed orchestration layer and processes payments with multiple processors. &nbsp;JustiFi’s processing partners include Fiserv Inc., First Data LLC and Stripe, Inc. which is a technical services provider and may offer the services as an agent of one or more financial institutions in the United States (each, a “Financial Services Provider”). The processing is carried out by the Processor. &nbsp;By accepting this Agreement, you are also accepting and agreeing to be bound by the Processor Terms. JustiFi is not a party to the Processor Terms and is not liable to you in respect thereof. By accepting this Agreement and the Processor Terms you are agreeing to the creation of an account with the Processor for Payment Processing (the “Processor Account”). We reserve the right to change the Processor, subject to the terms of our agreement with the Processor. In the event of any inconsistency between this Agreement and the Processor Terms, this Agreement shall prevail, except in the event of any inconsistency between this Agreement and the Processor Terms concerning Payment Processing or the Processor Account, in which case the Processor Terms shall prevail.</p>
            <p>The Processor’s role is to accept and process credit card, debit card and other types of payments with respect to sales of your products and services through internet-based transactions (“Card Not Present Transactions" or “CNP Transactions”). Your Role is to utilize the Services, you must be a business located in the United States.</p>

            <h4>The Payments Services</h4>
            <p>JustiFi hereby grants you a non-exclusive, non-transferable, non-sublicensable, limited, revocable right to use the Payments Services (the “License”). The License shall be for the term of this Agreement only. Neither the License nor any other provision hereof shall grant any rights in the Payments Services or other intellectual property rights except the limited License of use set out above.</p>
            <p>You shall not: (i) permit any third party to access the Payments Services, including, but not limited to, your JustiFi Admin on our website (the “JustiFi Admin”), except as permitted herein, and to carry out Transactions; (ii) create derivative works based on the Payments Services; (iii) copy, frame or mirror any part of the content of the Payments Services, other than copying or framing for your internal business purposes; (iv) reverse engineer, disassemble, decompile, or otherwise attempt to discover the source code or trade secrets for any of the Payments Services; or, (v) access the Payments Services in order to build a competitive product or service.</p>
            <p>It is your responsibility to obtain your customers’ consent to be billed for each Transaction or, as the case may be, on a recurring basis, in compliance with applicable legal requirements and Visa U.S.A. (“Visa”), MasterCard International Incorporated (“MasterCard”), American Express or other applicable Card networks’ (such networks being, collectively, the “Payment Networks”) payment rules (the “Payment Network Rules”).</p>

            <h4>Payment Methods</h4>
            <p>You assume sole and exclusive responsibility for the use of the Payments Services. You also assume sole and exclusive responsibility for Transactions under the Processor Terms. You are solely responsible for verifying the location and identity of customers and of the eligibility of a presented Card used to participate in your services, and JustiFi does not guarantee or assume any liability for Transactions authorized and completed that may later be reversed or charged back (see section D5 below). You are solely responsible for all reversed or charged back transactions regardless of the reason for, or timing of the reversal or chargeback. JustiFi or the Processor may add or remove one or more types of Payment Networks or Cards, in their sole discretion, at any time, without prior notice to you.</p>

            <h4>Customer Service</h4>
            <p>JustiFi will use its commercially reasonable efforts to provide you with customer support to help resolve issues relating to the Payments Services. The Processor retains sole and exclusive responsibility for Payment Processing of Transactions, and Settlement of funds. &nbsp;JustiFi retains responsibility for managing funds and releasing Payouts to all parties. &nbsp;You assume sole and exclusive responsibility for providing customer service or support to your customers for any and all issues related to your products and services, including, but not limited to, issues arising from the processing of Cards through the Payments Services.</p>

            <h4>Taxes</h4>
            <p>You have sole and exclusive responsibility to determine what, if any, taxes apply to the sale of your goods and services and/or the payments you receive in connection with your use of the Payments Services ("Taxes"). It is solely your responsibility to assess, collect, report, or remit the correct Taxes to the proper tax authority, whether in customers’ jurisdictions, your jurisdiction or elsewhere. We are not obligated to, nor will we, determine whether Taxes apply, or calculate, collect, report, or remit any Taxes to any tax authority, arising from any Transaction. JustiFi retains the right, but not the obligation, at its sole discretion, to complete and file tax or related reports with tax authorities regarding Transactions in those jurisdictions where JustiFi deems such reporting necessary. You hereby indemnify and hold JustiFi harmless from and against any and all liability related to Taxes and filings made by JustiFi in respect thereof. You agree that we may send you any tax-related information electronically.</p>

            <h4>Security</h4>
            <p>We maintain commercially reasonable administrative, technical and physical procedures to protect all the personal information regarding you and your customers that is stored in our servers from unauthorized access, accidental loss, or modification. JustiFi cannot, however, guarantee that unauthorized third parties will never be able to defeat those measures or use such personal information for improper purposes.</p>

            <h4>Data Security</h4>
            <p>You assume full responsibility for the security of data on your website or otherwise in your possession or control. You agree to comply with all applicable laws and rules in connection with your collection, security, and dissemination of any personal, financial, Card, or Transaction information (collectively, “Data", and as pertains to your customers, “Cardholder Data”). You agree that at all times you shall be compliant with applicable Payment Card Industry Data Security Standards (“PCI-DSS”) and, as applicable, the Payment Application Data Security Standards (“PA-DSS”). You agree to promptly provide JustiFi with documentation evidencing your compliance with PCI-DSS and/or PA-DSS upon request. You also agree that you will use only PCI-DSS and PA-DSS compliant service providers in connection with the storage or transmission of Card information, including a cardholder’s account number, expiration date, and CVV2. You must not store CVV2 data at any time. Information on PCI-DSS can be found on the PCI Council’s website. It is your responsibility to comply with these standards and all the Payment Network Rules.</p>

            <h4>Audit Right</h4>
            <p>If JustiFi believes that a security breach, personal data breach, or other compromise of data may have occurred, JustiFi may require you to have a third-party auditor that is approved by JustiFi conduct a security audit of your systems and facilities and issue a report to be provided to JustiFi and, at JustiFi’s discretion, to the Processor, its Financial Services Provider, Payment Networks, and law enforcement, at your sole cost and expense.</p>

            <h4>Restricted Use</h4>
            <p>You are required to obey all laws, rules, and regulations applicable to your use of the Payments Services (e.g., including those governing financial services, consumer protections, unfair competition, anti-discrimination, or false advertising). In addition to any other requirements or restrictions set forth in this Agreement, you shall not: (i) utilize the credit available on any Card to provide cash advances to cardholders; (ii) submit any Transaction for processing that does not arise from your sale of goods or service to a customer; (iii) act as a payment intermediary or aggregator or otherwise resell the Payments Services on behalf of any third party; (iv) send what you believe to be potentially fraudulent authorizations or fraudulent Transactions; or, (v) use the Payments Services or the Payment Processing services in a manner that a Payment Network reasonably believes to be an abuse of the Payment Network or a violation of the Payment Network Rules.</p>
            <p>You further agree not to permit any third party to do any of the following: (i) access or attempt to access our systems, programs, or data that are not made available for public use; (ii) copy, reproduce, republish, upload, post, transmit, resell, or distribute, in any way, material from us; (iii) permit any third party to use and benefit from the Payments Services via a rental, lease, timesharing, service bureau, or other arrangement; (iv) transfer any rights granted to you under this Agreement; (v) work around any of the technical limitations of the Payments Services, use any tool to enable features or functionalities that are otherwise disabled in the Payments Services, or decompile, disassemble, or otherwise reverse engineer the Payments Services, except to the extent that such restriction is expressly prohibited by law; (vi) perform or attempt to perform any actions that would interfere with the proper working of the Payments Services, prevent access to or use of the Payments Services by our other users, or impose an unreasonable or disproportionately large load on our infrastructure; or, (vii) otherwise use the Payments Services except as expressly allowed under this section.</p>

            <h4>Suspicion of Unauthorized or Illegal Use</h4>
            <p>We reserve the right to not provide the Payments Services in respect of any Transaction you submit that we believe, in our sole discretion, is in violation of this Agreement, any other JustiFi or Processor agreement, or exposes you, JustiFi, the Processor, or any other third party to actual or potential risk or harm, including, but not limited to, fraud and other criminal acts. You are hereby granting us authorization to share information with law enforcement about you, your Transactions, or your JustiFi Account.</p>

            <h4>Payment Network Rules</h4>
            <p>The Payment Networks have established guidelines, bylaws, rules, and regulations in the form of the Payment Network Rules. You are required to comply with all applicable Payment Network Rules. The Payment Network Rules for Visa, MasterCard and American Express are available on the Internet at the following links: Visa, MasterCard and American Express. The Payment Networks may amend the Payment Network Rules at any time and without notice to us or to you. Insofar as the terms of this Agreement and/or the Processor Terms are inconsistent with the Payment Network Rules, the Payment Network Rules shall prevail. We reserve the right to amend this Agreement at any time, with notice to you, as may be necessary to comply with the Payment Network Rules.</p>

            <h4>Disclosures and Notices</h4>
            <p>You agree that JustiFi can provide disclosures and notices, including tax forms, that we deem appropriate regarding the Payments Services to you by posting such disclosures and notices in your JustiFi Account, emailing them to the email address listed in your JustiFi Account, or mailing them to the address listed in your JustiFi Account. You also agree that electronic disclosures and notices have the same meaning and effect as if we had provided you with a paper copy.</p>

            <br />
            <h3 class="card-subtitle mb-2 text-muted" part="card-subtitle">B. Underwriting &amp; Obtaining a JustiFi Payments Services Account</h3>
            <br />

            <h4>Registration</h4>
            <p>The Payments Services are only made available to persons in United States that operate a business providing goods and/or services. You may not use the Payments Services for non-commercial, personal, family, or household purposes. To use JustiFi Payments for your business, you are required to register for a JustiFi Payments Account. When you register for a JustiFi Payments Account, we will collect information such as your name, your business or trade name, your address, email, phone number, business identification or registration number, and certain other information that we require including proof of location verification services, a legal opinion and other requirements . We may also collect personal information (including name, birthdate, and government-issued identification number) about your beneficial owners or principals.</p>
            <p>You may register as a corporation or other legal entity. &nbsp;You must be authorized to act on behalf of such entity, have the authority to bind the entity to this Agreement, and you must agree to this Agreement on behalf of such entity. If you have so agreed, the term "Merchant", “you” or “your” will mean that entity. You understand that by registering for a JustiFi Payments Account, you are also registering for a Processor Account under the Processor Terms and that you are simultaneously providing your information to JustiFi for the purpose of opening a JustiFi Payments Account, and to the Processor for the purpose of establishing your Processor Account.</p>

            <h4>Company Descriptions and Site URL</h4>
            <p>As part of your registration, you must provide the name under which you do business (which may be the business’ legal name or a "doing business name") (e.g. MyStore Online Widgets) and a billing descriptor. These two fields and your site URL may appear in your customers’ credit or debit card statements. To avoid customer confusion and Transaction disputes it is important that you enter a description that clearly identifies your business. You hereby agree to indemnify us from any costs, liabilities, losses, or expenses from disputes due to your failure to do so.</p>

            <h4>Verification and Underwriting</h4>
            <p>To verify your identity, we may require additional information, including your company registration number or business number, your HST, GST, or tax number, and, if applicable, your date of birth. We may also ask for additional information to help verify your identity and assess your business risk, including, but not limited, to a driver’s license or other government issued identification, or business license, for you or for any of the owners or principals of your business. We may ask you for your financial statements. We may request your permission to do a physical inspection at your place of business and to examine books and records that pertain to your compliance with this Agreement. We may ask for your permission to complete a background screen and/or credit check if deemed necessary to provide JustiFi Payment services which is determined by JustiFi. &nbsp;Your failure to comply with any of these requests may result in suspension or termination of your JustiFi Payments Account and the Processor Account. You authorize us to retrieve additional information about you from third parties and other identification services. We reserve the right to hold funds in your JustiFi Payments Account while awaiting the information requested above. JustiFi may use your information to apply for card merchant acquiring accounts on your behalf with certain Payment Networks (such as American Express).</p>
            <p>After we have collected and verified all your information, we will review your account and determine if you are eligible to use the Payments Services. We will notify you once your JustiFi Payments Account has been either approved or deemed ineligible for use of the Payments Services.</p>
            <p>By accepting the terms of this Agreement, you are providing us with authorization to retrieve information about you by using third parties, including credit bureaus and other information providers. You acknowledge that such information retrieved may include your name, address history, credit history, and other data about you. We may periodically update this information to determine whether you continue to meet the eligibility requirements for a JustiFi Payments Account.</p>
            <p>You agree that JustiFi is permitted to contact and share information about you and your application (including whether you are approved or declined), your JustiFi Payments Account, and the Processor Account with the Processor and other third parties in order to perform the Payments Services. This includes sharing information: (i) about Transactions for regulatory or compliance purposes; (ii) for use in connection with the management and maintenance of the Payments Services; (iii) to create and update our and their customer records about you, and to assist us and them in better serving you; and, (iv) to conduct our and their risk management process.</p>

            <h4>Designated Country</h4>
            <p>In registering for a JustiFi Payments Account, you are obliged to identify the location from where you are operating the business that will use the Payments Services in United States. By registering for a JustiFi Payments Account, you are confirming that you are either a legal resident of United States or you are duly established and, if necessary, registered or licensed as a business entity authorized to conduct business in United States. The Payments Services and JustiFi Payments Account may only be used in United States. By accepting this Agreement, you confirm that you will satisfy these requirements.</p>

            <br />
            <h3 class="card-subtitle mb-2 text-muted" part="card-subtitle">C. Processing Card Transactions, Managing Funds and Receiving Your Funds</h3>
            <br />

            <h4>JustiFi Payments Fees</h4>
            <p>You agree to pay the fees for processing that are set out in the Pricing Proposal.</p>
            <p>You are obligated to pay all applicable taxes, fees and other charges imposed by any governmental authority, including, without limitation, any value added tax, goods and services tax, harmonized sales tax and/or provincial or territorial sales tax, on the Payments Services provided under this Agreement. If you are tax-exempt, you will provide us with an appropriate certificate or other evidence of tax exemption that is satisfactory to us.</p>
            <p>We reserve the right to change the Fees subject to a thirty (30) day notice period.</p>
            <p>In addition to the Fees, you are also responsible for any penalties and fines imposed on you or on us by any bank, money services business, payment network, financial institution, or other financial intermediary resulting from your use of the Payments Services in a manner not permitted by this Agreement or by such financial intermediary’s rules and regulations.</p>

            <h4>Security Interest</h4>
            <p>As security for performance of your obligations under this Agreement, you grant us a first priority lien and security interest on all funds processed and deposited into all Payout Accounts (as defined in the Processor Terms), and any other bank accounts associated with your JustiFi Payments Account, and in any funds processed using the Payment Processing services. These security interests and liens will secure payment and performance of all of your obligations under this Agreement and any other agreements now existing or later entered into between us and you, including, without limitation, your obligation to pay any amounts due and owing to us. You will execute, deliver and pay the fees for any documents we request to create, perfect, maintain, and enforce this security interest.</p>

            <h4>Our Collection Rights</h4>
            <p>To the extent permitted by law, we may collect any obligations you owe us under this Agreement by requesting that the Processor deduct the corresponding amounts from the Reserve Account (as that term is defined below) or from funds payable to you arising from the settlement of Transactions. Fees will be assessed at the time a Transaction is processed and will be first deducted from the funds received for such Transaction. If these amounts are not sufficient to meet your obligations to us, we may collect these amounts from the bank account associated with your account. &nbsp;If these amounts are not sufficient to meet your obligations to us, we may charge the payment method associated with your JustiFi Account for any amounts owed to us. Your failure to fully pay amounts that you owe us on demand will be a breach of this Agreement. You will be liable for our costs associated with collection in addition to the amount owed, including, without limitation, attorneys’ fees and expenses, costs of any arbitration or court proceeding, collection agency fees, and any applicable interest.</p>
            <p>Additionally, we may require a personal guarantee from a principal of a business for funds owed under this Agreement. If we require a personal guarantee we will specifically inform you in advance.</p>
            <p>In addition to the amount due, delinquent accounts may be charged with fees that are incidental to the collection of delinquent accounts and chargebacks, including, but not limited to, collection fees and convenience fees and other third-party charges.</p>
            <p>You hereby explicitly agree that all communication in relation to delinquent accounts will be made by electronic mail or by phone, as provided to JustiFi by you. Such communication may be made by JustiFi or by anyone on its behalf, including, but not limited to, a third-party collection agent.</p>

            <h4>Reserves</h4>
            <p>Funds held in reserves are amounts of money set aside to cover chargebacks, refunds, or other payment obligations under this Agreement (the "Reserve Account"). We, in our discretion, will set the terms of your Reserve Account and notify you of such terms, which may require that a certain amount (including the full amount) of the funds received for a Transaction are held for a period of time, or that additional amounts are held in the Reserve Account, including but not limited to Reserve amounts that are required to obtain a JustiFi Payments Account. We, in our discretion, may elect to change the terms of the Reserve Account at any time, for any reason, based on your payment processing history or as requested by our payment processors.</p>
            <p>We may require you to fund the Reserve Account by means of: (i) any funds payouts made or due to you for Transactions submitted to the Payments Services; or, (ii) amounts available in your bank account by means of ACH debit to your JustiFi Payments Account; or, (iv) other sources of funds associated with your JustiFi Payments Account; or, (iv) requesting that you provide funds to us for deposit to the Reserve Account.</p>
            <p>You agree that: (i) you are not entitled to any interest or other compensation associated with the funds held in the Reserve Account; (ii) you have no right to direct that account; (iii) you have no legal interest in those funds or that account; and, (iv) you may not assign any interest in those funds or that account.</p>

            <h4>Contesting Chargebacks</h4>
            <p>You or JustiFi may elect to contest chargebacks assessed to your account. JustiFi may provide you with assistance, including notifications and software to help contest your chargebacks. We do not assume any liability for our role or assistance in contesting chargebacks.</p>
            <p>You grant us permission to share records or other information required with the cardholder, the cardholder’s financial institution, and your financial institution to help resolve any chargeback. You acknowledge that your failure to provide us with complete and accurate information in a timely manner may result in an irreversible chargeback being assessed.</p>
            <p>If the cardholder’s issuing bank or the Payment Network does not resolve a dispute in your favor, we may recover the chargeback amount and any associated fees from you as described in this Agreement.</p>
            <p>We reserve the right, upon notice to you, to charge a fee for mediating or investigating chargeback disputes.</p>

            <br />
            <h3 class="card-subtitle mb-2 text-muted" part="card-subtitle">D. Termination and Other Legal Terms</h3>
            <br />

            <h4>Term</h4>
            <p>The Agreement is effective upon the date you agree to it (by electronically indicating acceptance of the Partnership Proposal) and continues &nbsp;so long as you use the Payments Services or until terminated by you or by JustiFi.</p>

            <h4>Termination</h4>
            <p>We may terminate this Agreement and close your JustiFi Payments Account at any time, for any reason, upon notice to you. We may suspend your JustiFi Payments Account and your access to the Payments Services and any rights in respect of your JustiFi Payments Account, or terminate this Agreement, at any time, for any reason, including if: (i) we determine that you may be ineligible for the Payments Services because of the risk associated with your JustiFi Payments Account, including, without limitation, significant credit or fraud risk, or for any other reason; (ii) you do not comply with any of the provisions of this Agreement or the Processor Terms; or, (iii) upon request of the Payment Network, the Processor, or a Card issuer. Termination of the Processor Terms may, at the discretion of JustiFi, result in a termination of this Agreement. Termination of this Agreement shall entitle JustiFi to cause the Processor to terminate the Processor Terms.</p>

            <h4>Effects of Termination</h4>
            <p>Upon termination and closing of your JustiFi Payments Account, we will immediately discontinue your access to the Payments Services. You agree to complete all pending Transactions, immediately remove all logos for Cards, and stop accepting new Transactions through the Payments Services. You will not be refunded the remainder of any Fees that you have paid for the Payments Services if your access to or use of the Payments Services is terminated or suspended. Any funds in the Financial Services Provider’s custody will be paid out to you subject to the terms of your Payout Schedule (as defined in the Processor Terms).</p>
            <p>Termination does not relieve you of your obligations as defined in this Agreement, and the Processor may elect to continue to hold any funds deemed necessary, pending resolution of any other terms or obligations defined in this Agreement, including, but not limited to, chargebacks, fees, refunds, or other investigations or proceedings.</p>
            <p>Termination of this Agreement will not necessarily terminate your JustiFi Platform Terms, unless JustiFi determines otherwise.</p>

            <h4>Your Liability and Indemnification Concerning Liabilities</h4>
            <p>Nothing in this Agreement shall serve to diminish your liability under the Processor Terms or JustiFi Platform Terms. You are obliged to fulfill your obligations under this Agreement and those under the Processor Terms and JustiFi Platform Terms.</p>
            <p>JustiFi has agreed to indemnify and hold the Processor harmless for some, and, in some cases, all of your liabilities occurring under the Processor Terms, including, but not limited to, disputes (including, but not limited to, chargebacks), refunds, reversals, returns and fines (as such terms are defined in the Processor Terms). Insofar as JustiFi becomes liable to the Processor or any other third party for any penalties, fines, fees, or other liabilities under or in respect of the Processor Terms, the Payments Services, the Payment Processing services, or the Payment Network Rules, you agree to indemnify and hold JustiFi harmless from and against any and all such liabilities.</p>
            <p>Additionally, we may require a personal guarantee from a principal of a business for funds owed under this Agreement.</p>
            <p>You agree to indemnify and defend JustiFi against any claim, suit, demand, loss, liability, damage, action, or proceeding (each, a “Claim”) brought by a third party and you agree to fully reimburse JustiFi for any Claims that result from: (i) your breach of any provision of this Agreement; (ii) any fees, fines, penalties, disputes, reversals, returns, chargebacks (as such terms are defined in the Processor Terms), or any other liability we incur that results from your use of the Payments Services; (iii) negligent or willful misconduct of your owners, employees, contractors, or agents; (iv) contractual or other relationships between you and your customers; or, (v) third-party indemnity obligations we incur as a direct or indirect result of your acts or omissions, including, but not limited to, indemnification of the Processor or any Payment Network.</p>
            <p>We will have the final decision-making authority with respect to Claims, including, without limitation, claims for refunds for purchased items that are filed with us by you or your customers. You will be required to reimburse us for your liability. &nbsp;You will not receive a refund of any Fees paid to us.</p>
            <p>If you are liable for any amounts owed to us, we may immediately remove such amounts from your Reserve Account and deduct the amounts owed to us from such Reserve Account funds. If you do not have sufficient funds in the Reserve Account to cover your liability, you will be required to immediately add additional funds to your Reserve Account to cover funds owed to us. If you do not do so, we may engage in collections efforts to recover such amounts from you at your cost and expense.</p>

            <h4>Your Representations, Warranties and Covenants</h4>
            <p>You represent and warrant to us that: (i) you are at least eighteen (18) years of age, are authorized to act on behalf of the company, and have the authority to bind the company to this Agreement; (ii) you are eligible to register and use the Payments Services and have the right, power, and ability to enter into and perform under this Agreement; (iii) the name identified by you when you registered is your business name under which you sell goods and services and the information that you have provided to us is accurate and complete; (iv) you are not a member of an organized crime group, a party who has been a member of an organized crime group in the past five years, a quasi-member of an organized crime group, a corporate racketeer, or other similar party, nor are any of your officers or employees a member of the foregoing; and, (v) you will not carry out, nor use a third party to carry out, any of the following unlawful acts: (a) the act of making violent demands; (b) the act of making unreasonable demands exceeding legal responsibilities; (c) the act of using threatening behavior or violence in relation to a transaction; (d) the act of spreading rumors, using fraudulent means, or using force to harm the other party’s reputation or obstruct the party’s business; (e) the act of selling products for the purpose of money laundering; (f) the act of using a Card held by you for a sale without reasonable grounds or another act similar to those set forth in (a) through (f).</p>
            <p>You hereby covenant to us that: (i) any Transactions submitted by you will represent a bona fide sale by you; (ii) any Transaction submitted by you will accurately describe the goods and/or services sold and delivered to a customer; (iii) you will fulfill all of your obligations to each customer for which you submit a Transaction and will resolve any disputes or complaints directly with your customers; (iv) you and all Transactions initiated by you will comply with all applicable laws, rules, and regulations applicable to your business, including, but not limited to, any applicable tax laws and regulations; (v) except in the ordinary course of business, no Transaction submitted by you through the Payments Services will represent a sale to any principal, partner, proprietor, or owner of your entity; (vi) you will not use the Payments Services, directly or indirectly, for any fraudulent undertaking or in any manner so as to interfere with the use of the Payments Services; and, (vii) any information you provide to us will be accurate and complete.</p>
            <p>NO WARRANTIES THE PAYMENTS SERVICES AND ALL ACCOMPANYING DOCUMENTATION ARE PROVIDED ON AN “AS IS" AND “AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES, EITHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. USE OF THE PAYMENTS SERVICES IS AT YOUR OWN RISK.</p>
            <p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM OR THROUGH THE PAYMENTS SERVICES OR FROM: (I) JustiFi; (II) THE PROCESSOR, SUPPLIERS OR LICENSORS OF JustiFi OR THE PROCESSOR; OR, (III) ANY OF THE RESPECTIVE AFFILIATES, AGENTS, DIRECTORS, AND EMPLOYEES OF ANY OF THE ENTITIES LISTED IN (I) OR (II) ABOVE (COLLECTIVELY, THE “DISCLAIMING ENTITIES" AND INDIVIDUALLY, A “DISCLAIMING ENTITY”), WILL CREATE ANY WARRANTY. YOU SPECIFICALLY ACKNOWLEDGE THAT WE DO NOT HAVE ANY CONTROL OVER THE PRODUCTS OR SERVICES THAT ARE PAID FOR WITH THE PAYMENTS SERVICES, AND WE CANNOT ENSURE THAT YOUR CUSTOMERS WILL COMPLETE A TRANSACTION OR ARE AUTHORIZED TO DO SO.</p>
            <p>WITHOUT LIMITING THE FOREGOING, THE DISCLAIMING ENTITIES DO NOT WARRANT THAT: (I) THE INFORMATION THEY PROVIDE OR THAT IS PROVIDED THROUGH THE PAYMENTS SERVICES IS ACCURATE, RELIABLE OR CORRECT; (II) THE PAYMENTS SERVICES WILL MEET YOUR REQUIREMENTS; (III) THE PAYMENTS SERVICES WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (IV) THE PAYMENTS SERVICES WILL FUNCTION IN AN UNINTERRUPTED MANNER OR BE SECURE; (V) ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR, (VI) THE PAYMENTS SERVICES ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>
            <p>ANY SUBJECT MATTER DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE PAYMENTS SERVICES IS DOWNLOADED AT YOUR OWN RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOAD. THE DISCLAIMING ENTITIES MAKE NO REPRESENTATIONS OR WARRANTIES ABOUT HOW LONG WILL BE NEEDED TO COMPLETE THE PROCESSING OF A TRANSACTION.</p>
            <p>THE DISCLAIMING ENTITIES DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE PAYMENTS SERVICES, OR ANY HYPERLINKED WEBSITE OR SERVICE, OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND NEITHER JustiFi, &nbsp;THE PROCESSOR, NOR THE FINANCIAL SERVICES PROVIDER WILL BE A PARTY TO, OR IN ANY WAY MONITOR ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.</p>

            <h4>Limitation of Liability and Damages</h4>
            <p>IN NO EVENT SHALL A DISCLAIMING ENTITY BE LIABLE FOR ANY LOST PROFITS, LOSS OF DATA, OR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES ARISING OUT OF, IN CONNECTION WITH, OR RELATING TO THIS AGREEMENT OR THE PAYMENTS SERVICES, INCLUDING, WITHOUT LIMITATION, THE USE OF, INABILITY TO USE, OR UNAVAILABILITY OF THE PAYMENTS SERVICES. UNDER NO CIRCUMSTANCES WILL ANY OF THE DISCLAIMING ENTITIES BE RESPONSIBLE FOR ANY DAMAGE, LOSS OR INJURY RESULTING FROM HACKING, TAMPERING OR OTHER UNAUTHORIZED ACCESS OR USE OF THE PAYMENTS SERVICES OR YOUR JustiFi PAYMENTS ACCOUNT, OR THE INFORMATION CONTAINED THEREIN.</p>
            <p>THE DISCLAIMING ENTITIES ASSUME NO LIABILITY OR RESPONSIBILITY FOR AåNY: (I) PERSONAL INJURY OR PROPERTY DAMAGE OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF THE PAYMENTS SERVICES; (II) ANY UNAUTHORIZED ACCESS TO OR USE OF SERVERS USED IN CONNECTION WITH THE PAYMENTS SERVICES AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (III) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE PAYMENTS SERVICES; (IV) ANY SOFTWARE BUGS, VIRUSES, TROJAN HORSES, OR OTHER HARMFUL CODE THAT MAY BE TRANSMITTED TO OR THROUGH THE PAYMENTS SERVICES; (V) ANY ERRORS, INACCURACIES OR OMISSIONS IN ANY CONTENT OR INFORMATION, FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT OR INFORMATION, IN EACH CASE POSTED, EMAILED, STORED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE PAYMENTS SERVICES; AND/OR (VI) USER CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY.</p>
            <p>WITHOUT LIMITING THE FOREGOING PROVISIONS OF THIS SECTION D8, THE DISCLAIMING ENTITIES’ CUMULATIVE LIABILITY TO YOU SHALL BE LIMITED TO DIRECT DAMAGES, AND IN ALL EVENTS SHALL NOT EXCEED IN THE AGGREGATE THE AMOUNT OF FEES PAID BY YOU TO JustiFi DURING THE THREE (3) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM FOR LIABILITY.</p>
            <p>THIS LIMITATION OF LIABILITY SECTION APPLIES REGARDLESS OF THE LEGAL THEORY ON WHICH THE CLAIM IS BASED, INCLUDING, WITHOUT LIMITATION, CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER BASIS. THE LIMITATIONS APPLY EVEN IF JustiFi OR THE PROCESSOR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</p>
            <p>THE PROVISIONS OF THIS SECTION D8 SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</p>
            <p>The Payments Services are controlled and operated from facilities in the United States. We make no representations that the Payments Services are appropriate or available for use in other locations. Those who access or use the Payments Services from other jurisdictions do so at their own volition and are entirely responsible for compliance with all applicable United States, Canada, foreign and local laws and regulations, including, but not limited to, export and import regulations. You may not use the Payments Services if you are a resident of a sanctioned country embargoed by the United States, Canada, or the European Union, or are a foreign person or entity blocked or denied by the governments of the United States, Canada or the European Union.</p>

            <h4>Right to Amend</h4>
            <p>We have the right to change or add to the terms of this Agreement at any time, and to change, delete, discontinue, or impose conditions on any feature or aspect of the Payments Services or software with notice that we in our sole discretion deem to be reasonable in the circumstances. Any use of the Payments Services after our publication of any such changes shall constitute your acceptance of this Agreement as modified.</p>

            <h4>Assignment</h4>
            <p>This Agreement, and any rights and licenses granted hereunder, may not be transferred or assigned by you without our prior written consent, but may be assigned by us without consent or other restriction.</p>

            <h4>Change of Business</h4>
            <p>You agree to give us at least ninety (90) days prior notification of your intent to change your current product or services types, your business or trade name, or the manner in which you accept payment. You agree to provide us with prompt notification within one (1) day if you are the subject of any voluntary or involuntary bankruptcy or insolvency application, petition or proceeding, receivership, bankruptcy, or similar action or proceeding initiated by or against you or any of your principals (any of the foregoing, a “Bankruptcy Proceeding”). You also agree to promptly notify us within one (1) days of any adverse change in your financial condition, any planned or anticipated liquidation or substantial change in the basic nature of your business, any transfer or sale of twenty-five percent (25%) or more of your total assets, or any change in the control or ownership of your or your parent entity. You will also notify us within one (1) day of any judgment, writ, warrant of attachment or execution, or levy against twenty-five percent (25%) or more of your total assets.</p>
            <p>You will include us on the list and matrix of creditors as filed with any bankruptcy, commercial or civil court in connection with any Bankruptcy Proceeding, whether or not a claim may exist at the time of filing. Failure to do so will be cause for immediate termination of this Agreement and shall allow the pursuit of any other action available to us under the applicable Payment Network Rules or law.</p>

            <h4>Parties</h4>
            <p>This Agreement binds you and your respective heirs, representatives, and permitted and approved successors (including those by merger and acquisition), or any permitted assigns.</p>

            <h4>Third-Party Services and Links to Other Web Sites</h4>
            <p>You may be offered services, products, and promotions provided by third parties and not by us. If you decide to use these third-party services, you will be responsible for reviewing and understanding the terms and conditions associated with these services. You agree that we are not responsible for the performance of these services. &nbsp;The inclusion of any website link does imply an approval, endorsement, or recommendation by us. You agree that your access to any such website is at your own risk, and that the site is not governed by the terms and conditions contained in this Agreement. We expressly disclaim any liability for these websites. Please remember that when you use a link to go from our website to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our website, is subject to that website’s own rules and policies.</p>

            <h4>Force Majeure</h4>
            <p>No party will be liable for delays in processing or other non-performance caused by such events as fires, telecommunications failures, utility failures, power failures, equipment failures, labor strife, riots, war, terrorist attack, non-performance of our vendors or suppliers, acts of God, or other causes over which the respective party has no reasonable control, except that nothing in this section will affect or excuse your liabilities and obligations including, without limitation, for reversals, chargebacks, claims, fines, fees, refunds or unfulfilled products and services.</p>

            <h4>Entire Agreement and Remedies</h4>
            <p>These terms and conditions, and all policies and procedures that are incorporated herein by reference, constitute the entire agreement between you and JustiFi with respect to the provision of the Payments Services. Except as otherwise set out herein, in the event of a conflict between this Agreement and any other JustiFi or Processor agreement or policy, this Agreement shall prevail on the subject matter of this Agreement. Except as expressly provided in this Agreement, these terms describe the entire liability of JustiFi and our vendors and suppliers and sets forth your exclusive remedies with respect to the Payments Services and your access and use of the Payments Services. If any provision of this Agreement (or portion thereof) is held to be invalid or unenforceable under applicable law, then it shall be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law, and the remaining provisions will continue in full force and effect.</p>
            <p>This Agreement has been reviewed by you with the benefit of independent legal counsel to the extent you consider necessary, and any rule of construction to the effect that ambiguities are to be resolved against the drafting party shall not apply to the construction or interpretation of this Agreement. The rights conferred upon us in this Agreement are not intended to be exclusive of each other or of any other rights and remedies we may have at law or in equity. Rather, each and every right we may have under this Agreement, at law or in equity, is cumulative and concurrent, and in addition to every other right.</p>
            <p>This Agreement may be available in languages other than English. To the extent of any inconsistencies or conflicts between this English Agreement and the Agreements available in another language, the most current English version of the Agreement will prevail.</p>
          </div>
        </div >
      </div >
    );
  }
}
