/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JustifiCardForm {
        "iframeOrigin": string;
        "tokenize": (clientKey: string, account: string, paymentMethodMetadata: any) => Promise<unknown>;
    }
    interface JustifiPaymentsList {
        "accountId": string;
        "auth": { token?: string };
    }
}
export interface JustifiCardFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLJustifiCardFormElement;
}
declare global {
    interface HTMLJustifiCardFormElement extends Components.JustifiCardForm, HTMLStencilElement {
    }
    var HTMLJustifiCardFormElement: {
        prototype: HTMLJustifiCardFormElement;
        new (): HTMLJustifiCardFormElement;
    };
    interface HTMLJustifiPaymentsListElement extends Components.JustifiPaymentsList, HTMLStencilElement {
    }
    var HTMLJustifiPaymentsListElement: {
        prototype: HTMLJustifiPaymentsListElement;
        new (): HTMLJustifiPaymentsListElement;
    };
    interface HTMLElementTagNameMap {
        "justifi-card-form": HTMLJustifiCardFormElement;
        "justifi-payments-list": HTMLJustifiPaymentsListElement;
    }
}
declare namespace LocalJSX {
    interface JustifiCardForm {
        "iframeOrigin"?: string;
        "onCardFormBlur"?: (event: JustifiCardFormCustomEvent<any>) => void;
        "onCardFormChange"?: (event: JustifiCardFormCustomEvent<any>) => void;
        "onCardFormReady"?: (event: JustifiCardFormCustomEvent<any>) => void;
        "onCardFormTokenize"?: (event: JustifiCardFormCustomEvent<{ data: any }>) => void;
    }
    interface JustifiPaymentsList {
        "accountId"?: string;
        "auth"?: { token?: string };
    }
    interface IntrinsicElements {
        "justifi-card-form": JustifiCardForm;
        "justifi-payments-list": JustifiPaymentsList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "justifi-card-form": LocalJSX.JustifiCardForm & JSXBase.HTMLAttributes<HTMLJustifiCardFormElement>;
            "justifi-payments-list": LocalJSX.JustifiPaymentsList & JSXBase.HTMLAttributes<HTMLJustifiPaymentsListElement>;
        }
    }
}
