name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: build-publish
      uses: ./build_and_publish_storybook
      with:
        path: /docs
        build_command: yarn build-storybook
