name: Build and Publish Storybook to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - stencil-library/**
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: stencil-library
        run: yarn install --frozen-lockfile

      - name: Run unit tests (test:ci)
        working-directory: stencil-library
        run: |
          yarn install --frozen-lockfile
          yarn test

      - name: Run end-to-end tests
        working-directory: stencil-library
        run: yarn test:e2e

      - name: Build and Publish Storybook
        working-directory: stencil-library
        run: |
          yarn build:prod
          yarn build-storybook

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: storybook-artifact
          path: stencil-library/docs

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    env:
      IFRAME_ORIGIN: ${{ secrets.IFRAME_ORIGIN }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: storybook-artifact
          path: stencil-library/docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ github.token }}
