#https://medium.com/trackstack/deploying-a-react-app-to-aws-s3-with-github-actions-b1cb9ba75c95

name: Build and release React components
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - react-library/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-library
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'react-library/.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Yarn Install
        run: |
          yarn install

      - name: Typescript Compiling Build
        run: |
          yarn build
      - name: Publish to GitHub Registry
        run: |
            yarn publish --verbose --no-git-tag-version --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JUSTIFI_SUPPORT_NPM_TOKEN }}
