name: Build and Publish storybook to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - stencil-library/**
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    defaults:
      run:
        working-directory: stencil-library
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Build'
      shell: bash
      run: |
        echo "::group::Build"
        rm -rf node_modules
        yarn install --frozen-lockfile
        yarn build
        yarn build-storybook
        echo "::endgroup::"

    - name: 'upload'
      uses: actions/upload-pages-artifact@v1.0.8
      with: 
        path: ./docs
        
    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        token: ${{ github.token }}
