name: Build and Publish storybook to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - stencil-library/**
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test

      - name: Run end-to-end tests
        run: yarn test:e2e

      - name: Build and Publish Storybook
        run: |
          yarn build:prod
          yarn build-storybook

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: storybook-artifact
          path: ./docs

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    env:
      IFRAME_ORIGIN: ${{ secrets.IFRAME_ORIGIN }}
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: storybook-artifact
          path: ./docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ github.token }}
