name: Chromatic Deployment

on:
  pull_request:
    paths:
      - 'packages/webcomponents/**'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Run Chromatic
        working-directory: ./apps/docs
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
