# https://medium.com/trackstack/deploying-a-react-app-to-aws-s3-with-github-actions-b1cb9ba75c95

name: Production Build
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Yarn Install
        run: |
          yarn install

      - name: Typescript Compiling Build
        run: |
          yarn build

      - name: Rollup Production Build
        run: |
          yarn build:prod

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "dist"

      - name: Change index.js Cache-Control
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          aws s3 cp s3://${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}/index.js s3://${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}/index.js --metadata-directive REPLACE --cache-control "max-age=0" --acl public-read --content-type "text/javascript"

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: engineering-notifications
          status: Production Deployed
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: engineering-notifications
          status: Production Deploy failed
          color: danger


