name: Build and Publish storybook to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - stencil-library/**
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      IFRAME_ORIGIN: ${{ secrets.IFRAME_ORIGIN }}
      ENTITIES_API_ORIGIN: 'https://api.justifi.ai/v1'
      ENTITIES_AUTH_TOKEN: ''
      EXAMPLE_BUSINESS_ID: 'biz_3GCA2FgtShugA9O6dlLfH3'
      EXAMPLE_BUSINESS_ACCOUNT_ID: 'acc_5u5Dus39Meb1qqSsu5U7qS'
      PROXY_API_ORIGIN: 'https://wc-proxy.justifi.ai'
      PROXY_AUTH_TOKEN: ''
      EXAMPLE_PAYMENTS_ACCOUNT_ID: 'acc_1GBKS2rg7mLl2r3Ds4NPPY'
      EXAMPLE_PAYMENT_ID: 'py_76nDkjHlXOEFQue5o3tzMj'
      EXAMPLE_PAYOUT_ID: 'po_zBUZ6WvMEzoPzwS0qUmWE'
      PRIVATE_API_ORIGIN: 'https://api.justifi.ai/v1'
      PRIVATE_AUTH_TOKEN: ''
      EXAMPLE_PLATFORM_ACCOUNT_ID: 'acc_5u5Dus39Meb1qqSsu5U7qS'
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    defaults:
      run:
        working-directory: stencil-library
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Build'
        shell: bash
        run: |
          echo "::group::Build"
          rm -rf node_modules
          npm install --frozen-lockfile
          npm run build:prod
          npm run build-storybook
          echo "::endgroup::"
      - name: 'upload'
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: ./docs

      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ github.token }}
