name: Deploy Storybook to GitHub Pages
on:
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .env file from secrets
        shell: bash
        working-directory: ./apps/docs
        run: |
          echo "IFRAME_ORIGIN=${{ secrets.IFRAME_ORIGIN }}" >> .env
          echo "PROXY_API_ORIGIN=${{ secrets.PROXY_API_ORIGIN }}" >> .env

      - name: Create .env file from secrets
        shell: bash
        working-directory: ./packages/webcomponents
        run: |
          echo "IFRAME_ORIGIN=${{ secrets.IFRAME_ORIGIN }}" >> .env
          echo "PROXY_API_ORIGIN=${{ secrets.PROXY_API_ORIGIN }}" >> .env

      - name: 'Build'
        shell: bash
        run: |
          echo "::group::Build"
          pnpm clean
          pnpm install --frozen-lockfile
          pnpm build:mocks
          echo "::endgroup::"

      - name: 'upload'
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: ./apps/docs/storybook-static

      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ github.token }}
