name: Run Tests

on:
  pull_request:
    paths:
      - packages/webcomponents/**

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.7.5

      - name: NPM Install
        run: pnpm install

      - name: Run unit tests
        run: pnpm test

      - name: Create .env file from secrets
        shell: bash
        run: |
          cd ./packages/webcomponents
          echo "IFRAME_ORIGIN=${{ secrets.IFRAME_ORIGIN }}" >> .env
          echo "PROXY_API_ORIGIN=${{ secrets.PROXY_API_ORIGIN }}" >> .env

      - name: Run E2E tests
        run: pnpm test:e2e
