name: Run Tests

on:
  workflow_run:
    workflows: ['Install and Build']
    types:
      - completed

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: pnpm test
